export const SUPPORTED_LANGUAGES = [
    { name: "Afrikaans", code: "af" },
    { name: "Albanian", code: "sq" },
    { name: "Arabic", code: "ar" },
    { name: "Arabic (EGY)", code: "ar_EG" },
    { name: "Arabic (UAE)", code: "ar_AE" },
    { name: "Arabic (LBN)", code: "ar_LB" },
    { name: "Arabic (MAR)", code: "ar_MA" },
    { name: "Arabic (QAT)", code: "ar_QA" },
    { name: "Azerbaijani", code: "az" },
    { name: "Belarusian", code: "be_BY" },
    { name: "Bengali", code: "bn" },
    { name: "Bengali (IND)", code: "bn_IN" },
    { name: "Bulgarian", code: "bg" },
    { name: "Catalan", code: "ca" },
    { name: "Chinese (CHN)", code: "zh_CN" },
    { name: "Chinese (HKG)", code: "zh_HK" },
    { name: "Chinese (TAI)", code: "zh_TW" },
    { name: "Croatian", code: "hr" },
    { name: "Czech", code: "cs" },
    { name: "Danish", code: "da" },
    { name: "Dari", code: "prs_AF" },
    { name: "Dutch", code: "nl" },
    { name: "Dutch (BEL)", code: "nl_BE" },
    { name: "English", code: "en" },
    { name: "English (UK)", code: "en_GB" },
    { name: "English (US)", code: "en_US" },
    { name: "English (UAE)", code: "en_AE" },
    { name: "English (AUS)", code: "en_AU" },
    { name: "English (CAN)", code: "en_CA" },
    { name: "English (GHA)", code: "en_GH" },
    { name: "English (IRL)", code: "en_IE" },
    { name: "English (IND)", code: "en_IN" },
    { name: "English (JAM)", code: "en_JM" },
    { name: "English (MYS)", code: "en_MY" },
    { name: "English (NZL)", code: "en_NZ" },
    { name: "English (QAT)", code: "en_QA" },
    { name: "English (SGP)", code: "en_SG" },
    { name: "English (UGA)", code: "en_UG" },
    { name: "English (ZAF)", code: "en_ZA" },
    { name: "Estonian", code: "et" },
    { name: "Filipino", code: "fil" },
    { name: "Finnish", code: "fi" },
    { name: "French", code: "fr" },
    { name: "French (BEL)", code: "fr_BE" },
    { name: "French (CAN)", code: "fr_CA" },
    { name: "French (CHE)", code: "fr_CH" },
    { name: "French (CIV)", code: "fr_CI" },
    { name: "French (MAR)", code: "fr_MA" },
    { name: "Georgian", code: "ka" },
    { name: "German", code: "de" },
    { name: "German (AUT)", code: "de_AT" },
    { name: "German (CHE)", code: "de_CH" },
    { name: "Greek", code: "el" },
    { name: "Gujarati", code: "gu" },
    { name: "Hausa", code: "ha" },
    { name: "Hebrew", code: "he" },
    { name: "Hindi", code: "hi" },
    { name: "Hungarian", code: "hu" },
    { name: "Indonesian", code: "id" },
    { name: "Irish", code: "ga" },
    { name: "Italian", code: "it" },
    { name: "Japanese", code: "ja" },
    { name: "Kannada", code: "kn" },
    { name: "Kazakh", code: "kk" },
    { name: "Kinyarwanda", code: "rw_RW" },
    { name: "Korean", code: "ko" },
    { name: "Kyrgyz (Kyrgyzstan)", code: "ky_KG" },
    { name: "Lao", code: "lo" },
    { name: "Latvian", code: "lv" },
    { name: "Lithuanian", code: "lt" },
    { name: "Macedonian", code: "mk" },
    { name: "Malay", code: "ms" },
    { name: "Malayalam", code: "ml" },
    { name: "Marathi", code: "mr" },
    { name: "Norwegian", code: "nb" },
    { name: "Pashto", code: "ps_AF" },
    { name: "Persian", code: "fa" },
    { name: "Polish", code: "pl" },
    { name: "Portuguese (BR)", code: "pt_BR" },
    { name: "Portuguese (POR)", code: "pt_PT" },
    { name: "Punjabi", code: "pa" },
    { name: "Romanian", code: "ro" },
    { name: "Russian", code: "ru" },
    { name: "Serbian", code: "sr" },
    { name: "Sinhala", code: "si_LK" },
    { name: "Slovak", code: "sk" },
    { name: "Slovenian", code: "sl" },
    { name: "Spanish", code: "es" },
    { name: "Spanish (ARG)", code: "es_AR" },
    { name: "Spanish (CHL)", code: "es_CL" },
    { name: "Spanish (CO)", code: "es_CO" },
    { name: "Spanish (CRI)", code: "es_CR" },
    { name: "Spanish (DOM)", code: "es_DO" },
    { name: "Spanish (ECU)", code: "es_EC" },
    { name: "Spanish (HND)", code: "es_HN" },
    { name: "Spanish (MEX)", code: "es_MX" },
    { name: "Spanish (PAN)", code: "es_PA" },
    { name: "Spanish (PER)", code: "es_PE" },
    { name: "Spanish (SPA)", code: "es_ES" },
    { name: "Spanish (URY)", code: "es_UY" },
    { name: "Swahili", code: "sw" },
    { name: "Swedish", code: "sv" },
    { name: "Tamil", code: "ta" },
    { name: "Telugu", code: "te" },
    { name: "Thai", code: "th" },
    { name: "Turkish", code: "tr" },
    { name: "Ukrainian", code: "uk" },
    { name: "Urdu", code: "ur" },
    { name: "Uzbek", code: "uz" },
    { name: "Vietnamese", code: "vi" },
    { name: "Zulu", code: "zu" }
];
